apiVersion: v1
kind: Service
metadata:
  name: hidoldori-service-a
  labels:
    app: hidoldori-service-a
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: hidoldori-service-a
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hidoldori-service-a
  labels:
    app: hidoldori-service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hidoldori-service-a
  template:
    metadata:
      labels:
        app: hidoldori-service-a
    spec:
      containers:
        - name: hidoldori-service-a
          image: gcr.io/burnished-mark-311301/hidoldori-service-a:0.4
          ports:
            - containerPort: 8081